openapi: 3.0.3
info:
  version: 8.12.0
  title: "@fastify/swagger"
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: __Secure-Authorization
      description: Default cookie authorization
  schemas:
    def-0:
      type: string
      minLength: 32
      maxLength: 32
      title: authentication
    def-1:
      type: integer
      minimum: 1
      maximum: 32767
      title: positive_smallint
    def-2:
      type: integer
      minimum: -32767
      maximum: 32767
      title: smallint
    def-3:
      type: integer
      minimum: 0
      title: uint
    def-4:
      type: integer
      minimum: 0
      maximum: 32767
      title: usmallint
    def-5:
      type: string
      minLength: 5
      pattern: "[A-Z]"
      title: login
    def-6:
      type: string
      minLength: 5
      pattern: "[\\W0-9]"
      title: password
paths:
  /serverstatus:
    get:
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  metrics:
                    type: object
                    properties:
                      eventLoopDelay:
                        type: number
                      rssBytes:
                        type: number
                      heapUsed:
                        type: number
                      eventLoopUtilized:
                        type: number
                  uptime:
                    type: number
  /favicon.ico:
    get:
      responses:
        "200":
          description: Default Response
  /apple-touch-icon.png:
    get:
      responses:
        "200":
          description: Default Response
  /robots.txt:
    get:
      responses:
        "200":
          description: Default Response
  /sitemap.xml:
    get:
      responses:
        "200":
          description: Default Response
  /accounting:
    get:
      responses:
        "200":
          description: Default Response
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - authentication
              additionalProperties:
                $ref: "#/components/schemas/def-3"
              properties:
                authentication:
                  $ref: "#/components/schemas/def-0"
        required: true
      responses:
        "200":
          description: Default Response
  /employees:
    get:
      responses:
        "200":
          description: Default Response
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - login
                - password
                - access
                - authentication
              additionalProperties: false
              properties:
                id:
                  $ref: "#/components/schemas/def-3"
                login:
                  $ref: "#/components/schemas/def-5"
                password:
                  $ref: "#/components/schemas/def-6"
                access:
                  type: string
                  enum:
                    - ADMIN
                    - CEO
                    - CURATOR
                    - STREAMER_UNILIVE
                    - STREAMER_BACKSTAGE
                streams:
                  type: array
                  uniqueItems: true
                  items:
                    type: string
                    enum:
                      - STREAM_1
                      - STREAM_2
                      - STREAM_3
                responsibility:
                  type: string
                  enum:
                    - ""
                    - GROUP_1
                    - GROUP_2
                    - GROUP_3
                authentication:
                  $ref: "#/components/schemas/def-0"
        required: true
      responses:
        "200":
          description: Default Response
  /validate:
    get:
      parameters:
        - schema:
            $ref: "#/components/schemas/def-5"
          in: query
          name: login
          required: true
        - schema:
            $ref: "#/components/schemas/def-6"
          in: query
          name: password
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                required:
                  - valid
                additionalProperties: false
                properties:
                  valid:
                    type: boolean
  /login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - login
                - password
                - authentication
              additionalProperties: false
              properties:
                login:
                  $ref: "#/components/schemas/def-5"
                password:
                  $ref: "#/components/schemas/def-6"
                authentication:
                  $ref: "#/components/schemas/def-0"
        required: true
      responses:
        "200":
          description: Default Response
  /logout:
    get:
      responses:
        "200":
          description: Default Response
  /:
    get:
      responses:
        "200":
          description: Default Response
  /streamers:
    get:
      responses:
        "200":
          description: Default Response
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - unique_id
                - status
                - category
                - stream
                - streamer_group
                - pledge
                - authentication
              additionalProperties: false
              properties:
                id:
                  $ref: "#/components/schemas/def-3"
                unique_id:
                  type: string
                password:
                  type: string
                  maxLength: 50
                status:
                  type: string
                  enum:
                    - CONTRACT
                    - PREPARATION
                    - ACTIVE
                    - PAUSED
                    - FIRED
                category:
                  type: string
                  enum:
                    - OUR
                    - BACKSTAGE
                    - OUTSIDE
                    - ETC
                stream:
                  type: string
                  enum:
                    - STREAM_1
                    - STREAM_2
                    - STREAM_3
                streamer_group:
                  type: string
                  enum:
                    - GROUP_1
                    - GROUP_2
                    - GROUP_3
                pledge:
                  $ref: "#/components/schemas/def-3"
                authentication:
                  $ref: "#/components/schemas/def-0"
        required: true
      responses:
        "200":
          description: Default Response
servers:
  url: https://localhost.xyz
  description: Main server
